services:
  angular-app:
    build: .
    container_name: bloomcycle-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./:/angular-app
      - /angular-app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "start"]