name: Backend CI

on:
  push:
    branches: [ master ]
    paths:
      - 'bloomcycle-backend/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'bloomcycle-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: bloomcycle_test
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'corretto'
        cache: maven

    - name: Build and Test
      working-directory: ./bloomcycle-backend
      run: |
        mvn clean verify
      env:
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/bloomcycle_test
        SPRING_DATASOURCE_USERNAME: test_user
        SPRING_DATASOURCE_PASSWORD: test_password
        JWT_SECRET: ${{ secrets.JWT_SECRET }}

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: bloomcycle-backend/target/surefire-reports

    - name: Build Docker image
      if: github.ref == 'refs/heads/main'
      working-directory: ./bloomcycle-backend
      run: |
        docker build -t bloomcycle-backend .

    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag bloomcycle-backend ${{ secrets.DOCKERHUB_USERNAME }}/bloomcycle-backend:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/bloomcycle-backend:latest